spring:
  application:
    name: ibnv

  datasource:
    #    url: jdbc:mysql://127.0.0.1:3306/ibnv
    #    username: root
    #    password:

    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sql:
    init:
      mode: always

  flyway:
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_EMAIL}
    password: ${SPRING_EMAIL_PASSWORD}
    default-encoding: UTF-8

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}

admin:
  secret: ${ADMIN_SECRET}

  #https://myaccount.google.com/apppasswords?rapt=AEjHL4No8pcg1owQ0k-oADCTa7DhyqIC290oAmNDwuqTdyLchqX1cCW1FzThiy74_6ZWbc128HLfWnV0HciCjDTrmr6KC16b_zdX5Jc4bfPf1GWgEQFD8NY